### ISSUE TITLE
Uncomplete Theme?

### ISSUE THREAD

**Issue by MrWelsch** [bitsper2nd/merge-monokai-theme#1]
Hello,

first of all thank you for making this theme.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/45096895/144815056-efe8d04b-6e13-4f46-a497-6399693eea0f.png">

The main window (Summary Tab) as well as the code syntax do not seem to change as expected?

**Comment by bitsper2nd** [comment]
Hi, did you add the [related color schemes](https://github.com/bitsper2nd/sublime-monokai-scheme) to the Packages folder? You can download the color schemes in either the Sublime Text/Packages or Sublime Merge/Packages to get the Theme fully working on Sublime Merge
![image](https://user-images.githubusercontent.com/22452474/144903059-9272da43-f9c6-4902-9e64-ddd65cc970f9.png)

This is Sublime Merge with fully working Monokai Plus (Octagon) theme set on the preferences.
![image](https://user-images.githubusercontent.com/22452474/144903778-9e7766bf-eecf-474f-98e6-c0a9d3067cd3.png)

**Comment by MrWelsch** [comment]
I just double checked.

First I tried the linked rep containing the sublime-color-schemes. While using those all I could see was an entirely black window.

Then I cloned the sublime-theme rep again and put them in the package folder like before. Same issue.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/45096895/144971158-0a56ed11-ab2c-4c4c-91ee-4da9ec597525.png">

Also this is my preferences file:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/45096895/144970778-2fef5a3e-1d3d-4514-bd10-97dd7728914f.png">

**Comment by bitsper2nd** [comment]
It works fine on my side. This is the Spectrum Color Scheme on Sublime Text and the Theme on Sublime Merge.
![image](https://user-images.githubusercontent.com/22452474/145018524-63920fd6-b0f4-4e6e-abde-d98ae0f7d635.png)

Clone both git repositories this time on the Sublime Merge Packages folder. They should be separate folders. One with the [Color Schemes](https://github.com/bitsper2nd/sublime-monokai-scheme.git) and the other with the [Themes](https://github.com/bitsper2nd/merge-monokai-theme.git). 
![image](https://user-images.githubusercontent.com/22452474/145019009-b1560402-859f-4555-9246-3efcef2caeb5.png)

**Comment by MrWelsch** [comment]
I just did that 

<img width="757" alt="image" src="https://user-images.githubusercontent.com/45096895/145098011-090f63ce-e64b-4a3f-822e-233dfbd6cccc.png">

and edited the `Preferences.sublime-settings` :

<img width="769" alt="image" src="https://user-images.githubusercontent.com/45096895/145098173-561b72e0-9ec2-4548-ab1c-b0266c89cb5d.png">

It's the same syntax I used to configure sublime text, except there I used the original Monokai Pro Theme.

Now I get proper syntax highlighting inside the code blocks but still have the basic dark theme from sublime in the background.

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/45096895/145098713-3a9ae237-4ec5-471d-8863-f48a0e9a8973.png">

Maybe thats because of this:

`"extends": "Merge.sublime-theme",` 

or some style property thats different on mac as compared to windows?

**Comment by bitsper2nd** [comment]
Okay let me be more clear. Step by step:

- Open a new tab in Sublime Merge. Clone the theme [repository](https://github.com/bitsper2nd/merge-monokai-theme.git) in Sublime Merge/Packages.

![image](https://user-images.githubusercontent.com/22452474/145101930-4b938d05-ea80-4dfb-95c8-aeabed91ca63.png)

- Open another tab in Sublime Merge. Clone the color scheme [repository](https://github.com/bitsper2nd/sublime-monokai-scheme.git) in Sublime Text/Packages or in Sublime Merge Packages.

![image](https://user-images.githubusercontent.com/22452474/145102454-f91e688d-2501-4e36-9403-a6a658820d7a.png)

- Do not change or remove the files from the cloned repositories. They must be there for the theme to work. 

![image](https://user-images.githubusercontent.com/22452474/145103202-e7a03d88-abca-42d4-82a3-963b94afcc50.png)

- Edit the Sublime Merge settings. The only thing you need to do is change the theme name. There is no need to add the color scheme in the SM settings.

![image](https://user-images.githubusercontent.com/22452474/145103034-77741d80-2bdc-4077-be53-fc6e7105982d.png)

If you follow these instructions, the theme should work.

**Comment by MrWelsch** [comment]
Thanks for the step by step guide.

Maybe I should be more clear as well:

If I try another filter, say Plus it looks as expected

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/45096895/145113690-50244456-1759-4e53-b1e0-3ee62d13b882.png">

But if I use spectrum it looks like this:

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/45096895/145113759-21319fb8-2cf2-4d9a-bd61-a4a1d055c6f4.png">

Now the background in the summary window is not part of the spectrum theme which leads me to believe that there is some property missing in the theme or it is set to the wrong color.

**Comment by bitsper2nd** [comment]
That's really weird. All of them work for me. Here is a clip showing each Monokai theme variant.

https://user-images.githubusercontent.com/22452474/145126669-36403e4d-b492-4d86-8d43-2a464c89b6cf.mp4

Possible solutions:
- Close and reopen Sublime Merge
- Make sure you have all the the Color Schemes/Themes files
- Add this line to your SM settings: `"theme": "Monokai Plus (Spectrum).sublime-theme"`

**Comment by MrWelsch** [comment]
At this point all I can say is thank you for your support but I really do not think that the problem is on my end, since the other themes work and this isn't the first theme I have used.
Additionally I've already re-cloned the rep multiple times and have done several other steps.
