### ISSUE TITLE
Scrollbar in Quick Switch Repository is un-themed

### ISSUE THREAD

**Issue by deathaxe** [bitsper2nd/merge-monokai-theme#3]
![grafik](https://user-images.githubusercontent.com/16542113/191940181-04770db9-13a8-4ead-aebe-5e136be5658c.png)

**Comment by bitsper2nd** [comment]
Updated the scroll bar/puck in the Switch Project panel. Does this look good?

Before
![scrollbar-puck-switch-panel-old](https://user-images.githubusercontent.com/22452474/192008432-d5a826a4-feab-419c-95be-eab71317b570.png)


After
![scrollbar-puck-switch-panel](https://user-images.githubusercontent.com/22452474/192008556-b62d59d9-bf6d-4c91-b571-084f8b468b34.png)

**Comment by deathaxe** [comment]
Great! Thanks.
