### ISSUE TITLE
Theme Doesn't Change

### ISSUE THREAD

**Issue by sylido** [bitsper2nd/merge-monokai-theme#4]
Seems like the recent changes to add the Cognition theme and the color schemes as part of the project kinda broke things for me. Changing the Themes doesn't change the theme, unless I switch from the included Sublime Merge ones to the Monokai Plus ones - but it's always the same theme color - blueish.

**Comment by jfcherng** [comment]
Do you use the exact `"theme": "Monokai Plus.sublime-theme"` rather than a custom theme extending them? That's what I encountered.

**Comment by sylido** [comment]
I tried all the themes, they don't seem to get loaded even if I restart sublime merge. The color schemes that I downloaded separately and defined in the preferences do work as expected though.

**Comment by jfcherng** [comment]
If your SM setup is not too complicate, maybe you can try to use this theme from a clean state (like safe mode). It this theme works, then subsequently add back your customizations.

**Comment by sylido** [comment]
I think it might be related to the refactoring of the themes in some way, I remember that the old versions worked, I might just have to checkout an old commit to verify - is there a verbose mode that would show me if there are any errors ?

**Comment by bitsper2nd** [comment]
I made several changes for this theme. At the start you needed to have the [related color schemes](https://github.com/bitsper2nd/sublime-monokai-scheme) for it to work.

That changed with commit [cc7ee28fc457f7028875403a57a74144d9245dd7](https://github.com/bitsper2nd/merge-monokai-theme/commit/cc7ee28fc457f7028875403a57a74144d9245dd7).  Now it is included with the theme. 

Now my educated guess is that you might be using an outdated version of the color scheme. That can affect the theme. Try pulling the new changes.

**Comment by sylido** [comment]
hey @bitsper2nd I did test out with the included color schemes and the separate ones - in both cases I wasn't getting a change in the visuals. I just changed the settings value to reference the correct path for the new/old themes.

I changed it to just the name of the color scheme and it did seem to change this time to the Cognition theme/color scheme - trying to change it to the Spectrum one and restarting Merge didn't result in any change. Here are my settings - maybe I'm doing something wrong there

> 	"always_show_command_status": true,
	"editor_path": "C:\\Program Files\\Sublime Text 3\\sublime_text.exe",
	"hardware_acceleration": "opengl",
	"hide_menu": false,
	"render_commit_dialog_message_at_top": true,
	"side_bar_layout": "locations_as_column",
	"theme": "Monokai Plus (Spectrum).sublime-theme",
	"color_scheme": "Monokai Plus (Spectrum).sublime-color-scheme",
	"themed_title_bar": true,
	"time_format": "24h",
	"trim_trailing_white_space_on_save": true,
	"font_size": 5,
	"tab_size": 2,
	"translate_tabs_to_spaces": true,
	"auto_diff_style_min_chars": 140,
	"ignore_diff_white_space": false,

**Comment by bitsper2nd** [comment]
sorry for the late reply. I made a few changes to your preferences:
1. change the font size
2. added extra slash to the ST3 PATH
3. removed the color scheme

It worked for me. Here are the lines:
```
{
	"always_show_command_status": true,
	"editor_path": "C:Program Files\\Sublime Text 3\\sublime_text.exe",
	"hardware_acceleration": "opengl",
	"hide_menu": false,
	"render_commit_dialog_message_at_top": true,
	"side_bar_layout": "locations_as_column",
	"theme": "Monokai Plus (Spectrum).sublime-theme",
	"themed_title_bar": true,
	"time_format": "24h",
	"trim_trailing_white_space_on_save": true,
	"font_size": 14,
	"tab_size": 2,
	"translate_tabs_to_spaces": true,
	"auto_diff_style_min_chars": 140,
	"ignore_diff_white_space": false,
}
```

![image](https://user-images.githubusercontent.com/22452474/197630453-0322c390-2746-4bf3-8fe1-7e49f6231177.png)

**Comment by sylido** [comment]
Tried with your changes but still didn't work.

Seems like I misread the guide, the Monokai Theme directory has to be in the Packages directory not the Packages/User directory - moving it there fixed the issue, not sure how it worked on my previous install there.

Thank you so much - pretty colors all around !
